### ISSUE TITLE
Task

### ISSUE THREAD

**Issue by JohnKhandygo** [katorina/EnglishCheckers#1]
**Общая формулировка**
Разработать программу с графическим интерфейсом, реализующую указанную в задании функциональность, на языках Java и/или Kotlin. При проектировании использовать объектно-ориентированный подход. Разработать автоматические тесты для отдельных частей программы. Написанный код держать в отдельном проекте или модуле в репозитории на GitHub.

**Английские шашки**
Реализовать игру Английские шашки для двух игроков за одним компьютером, с графическим интерфейсом. Реализовать все правила игры и проверить их работоспособность тестами. Правила [здесь](https://ru.wikipedia.org/wiki/Английские_шашки).

**Comment by JohnKhandygo** [comment]
- [ ] Отсутствуют тесты. 
- [ ] Не все правила реализованы.
- [ ] Нет условию остановки игры.
- [ ] Хотелось бы иметь хотя бы опцию "начать заново".

**Comment by katorina** [comment]
Если исправить все замечания, но без тестов, оценка 3 будет?

**Comment by JohnKhandygo** [comment]
Да.

**Comment by JohnKhandygo** [comment]
Зачтено на 3.5. Итого 4 за курсовой проект.
